spring:
  profiles:
    include:
      - datasource
      - log

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'kingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungilkingseungil'|base64
  secret: a2luZ3NldW5naWxraW5nc2V1bmdpbGtpbmdzZXVuZ2lsa2luZ3NldW5naWxraW5nc2V1bmdpbGtpbmdzZXVuZ2lsa2luZ3NldW5naWxraW5nc2V1bmdpbGtpbmdzZXVuZ2lsa2luZ3NldW5naWxraW5nc2V1bmdpbGtpbmdzZXVuZ2lsa2luZ3NldW5naWxraW5nc2V1bmdpbGtpbmdzZXVuZ2lsCg==

  token-validity-in-seconds: 86400